name: Picf
channels:
  - conda-forge
  - defaults
dependencies:
  #- python=3.8.5
  - python=3.6
  
  - dlib=19.22
  - opencv=4.0.1
  - pip=21.3.1
  - networkx=2.5
  - numpy=1.16.2
  - scipy=1.2.1
  #- pillow=8.4.0
  - tqdm=4.56.0
  - scikit-learn=1.0.1
  - PyWavelets=1.1.1
  - backcall==0.2.0
  - decorator==4.4.2
  - ipykernel==5.4.3
  - ipython==7.19.0
  - ipython-genutils==0.2.0
  - jedi==0.18.0
  - jupyter-client==6.1.11
  - jupyter-core==4.7.0
  - parso==0.8.1
  - pexpect==4.8.0
  - pickleshare==0.7.5
  - prompt-toolkit==3.0.10
  - ptyprocess==0.7.0
  - Pygments==2.7.4
  - python-dateutil==2.8.1
  - pyzmq==21.0.1
  - six==1.15.0
  - tornado==6.1
  - traitlets==5.0.5
  - wcwidth==0.2.5
  - python-dotenv==0.15.0
  - ipyplot==1.1.0
  - torch==1.7.1
  - torchvision==0.8.2
  - ftfy==5.8
  - regex==2020.11.13
  - pandas==1.5.2
  - fastparquet==0.5.0
  - pyarrow==2.0.0 
  - pip:
    - imutils==0.5.4
    - PySide6==6.2.1
 #   - tensorflow==2.7.0
    -tensorflow==1.7.0
#    - pytorch==1.13.0
#prefix: C:\Users\Yashaswi\anaconda3\envs\sorter